const cacheName = 'pravoslavlje-v7'; // Povećaj na v5 da telefon osveži memoriju
const assets = [
  './',
  './index.html',
  './manifest.json',
  './svetitelji.json',
  './ikona.png',
  './papir.jpg', 
  './papir.png', 
   './matej.html',
  './marko.html',
  './luka.html',
  './jovan.html',
   './serafimi.png',
  './sabor.png', 
  './krst.png',
  './snaga.png',
  './tisina-snaga.png',
  './bogorodica-pehar.png',
  './bogorodica.png',
  './andjeo.png',
  './bog-cuti.png',
  './bogorodica-hrist.png',
 './bozija-volja.png',
  './hram.png',
  './isceliteljka.png',
  './krst-ornament-veliki.png',
  './mojstiker.png',
  './oprostaj.png',
  './pokajnik.png',
  './prastaj-i-ljubi.png',
 './ljubi-i-prastaj.png',
  './stiker-bog.png',
  './sve-primi-mirno.png',
  './svako-dobro.png',
  './trojerucica.png',
  './pricest.png',
  './gospode-oprosti-i-osvetli-mi-put.png',
  './tisina-snaga.png',
  './bogojavljenje.jpg',
  './blagovesti.jpg',
  './bozic.jpg',
  './cveti.jpg',
  './djurdjevdan.jpg',
  './duhovski-ponedeljak.jpg',
  './duhovski-utorak.jpg',
  './blagovesti.jpg',
  './ivanjdan.jpg',
  './jovankrstitelj.jpg',
 './kirilo-metodije.jpg',
  './justin.jpg',
  './konstantin-jelena.jpg',
  './krstovdan.jpg',
  './mala-gospojina.jpg',
  './mitrovdan.jpg',
  './nikolaj.jpg',
  './nikoljdan.jpg',
  './petar-cetinjski.jpg',
  './petrovdan.jpg',
  './preobrazenje.jpg',
  './prorok-ilija.jpg',
  './sabor.jpg',
  './silazak-duha-svetoga.jpg',
  './sv-sava.jpg',
  './sveta-petka.jpg',
  './sveta-tri-jerarha.jpg',
  './sveti-prvomucenik-stefan.jpg',
  './sveti-vasilije-veliki.jpg',
  './usekovanje.jpg',
  './uspenije.jpg',
 './vasilije-ostroski.jpg',
  './vaskrs.jpg',
  './vaskrsni-ponedeljak.jpg',
  './vaskrsni-utorak.jpg',
  './vavedenje.jpg',
  './vaznesenje.jpg',
  './veliki-petak.jpg',
  './vidovdan.jpg',
  
  './psaltir.html',
  './molitvenik.html',
  './novi-zavet.html',
  './ohridski-prolog.html',
  './duhovne-pouke.html',
  './duhovne-poucne-price.html',
  './praznici.html',
  './post-i-trapave-sedmice.html',
  './vaskrsnji-kalendar.html',
  './januar-2026.html',
  './februar-2026.html',
  './mart-2026.html',
  './april-2026.html',
  './maj-2026.html',
  './jun-2026.html',
  './jul-2026.html',
  './avgust-2026.html',
  './septembar-2026.html',
  './oktobar-2026.html',
  './novembar-2026.html',
  './decembar-2026.html',
  './prolog-januar.html',
  './prolog-februar.html',
  './prolog-mart.html',
  './prolog-april.html',
  './prolog-maj.html',
  './prolog-jun.html',
  './prolog-jul.html',
  './prolog-avgust.html',
  './prolog-septembar.html',
  './prolog-oktobar.html',
  './prolog-novembar.html',
  './prolog-decembar.html',
  './jovan.html',
  './jovan-1.html',
  './jovan-2.html',
  './jovan-3.html',
  './jovan-4.html',
  './jovan-5.html',
  './jovan-6.html',
  './jovan-7.html',
  './jovan-8.html',
  './jovan-9.html',
  './jovan-10.html',
  './jovan-11.html',
  './jovan-12.html',
  './jovan-13.html',
  './jovan-14.html',
  './jovan-15.html',
  './jovan-16.html',
  './jovan-17.html',
  './jovan-18.html',
  './jovan-19.html',
  './jovan-20.html',
  './jovan-21.html',
  './matej.html',
  './matej-1.html', './matej-2.html', './matej-3.html', './matej-4.html', './matej-5.html',
  './matej-6.html', './matej-7.html', './matej-8.html', './matej-9.html', './matej-10.html',
  './matej-11.html', './matej-12.html', './matej-13.html', './matej-14.html', './matej-15.html',
  './matej-16.html', './matej-17.html', './matej-18.html', './matej-19.html', './matej-20.html',
  './matej-21.html', './matej-22.html', './matej-23.html', './matej-24.html', './matej-25.html',
  './matej-26.html', './matej-27.html', './matej-28.html',
 './marko.html',
  './marko-1.html', './marko-2.html', './marko-3.html', './marko-4.html', './marko-5.html',
  './marko-6.html', './marko-7.html', './marko-8.html', './marko-9.html', './marko-10.html',
  './marko-11.html', './marko-12.html', './marko-13.html', './marko-14.html', './marko-15.html', 
  './marko-16.html',
  './luka.html',
  './luka-1.html', './luka-2.html', './luka-3.html', './luka-4.html', './luka-5.html',
  './luka-6.html', './luka-7.html', './luka-8.html', './luka-9.html', './luka-10.html',
  './luka-11.html', './luka-12.html', './luka-13.html', './luka-14.html', './luka-15.html',
  './luka-16.html', './luka-17.html', './luka-18.html', './luka-19.html', './luka-20.html',
  './luka-21.html', './luka-22.html', './luka-23.html', './luka-24.html',
  // MOLITVE IZ MOLITVENIKA:
  './o-molitvi-sv-jovan-krostantski.html',
  './jutarnje-molitve.html',
  './molitveno-pravilo-serafima-sarovskog.html',
  './bogorodice-djevo.html',
  './simbol-vere.html',
  './molitva-za-decu.html',
  './molitva-za-roditelje.html',
  './molitva-za-otvorenje-uma.html',
  './molitva-svetog-filareta.html',
  './velikoposna-molitva-svetog-jefrema-sirina.html',
  './molitva-pokajnika.html',
  './molitve-andjelu-cuvaru.html',
  './molitva-isusu-hristu.html',
  './molitve-svetim-arhangelima-za-svaki-dan-u-nedelji.html',
  './molitve-presvetoj-bogorodici-za-svaki-dan-u-nedelji.html',
  './molitva-za-spasenje-od-rasejanosti-uma.html',
  './molitva-bogorodici.html',
  './molitva-u-tuzi-dusevnoj.html',
  './molitva-za-upokojene.html',
  './molitva-za-upokojene-prestavljenih.html',
  './molitva-za-zastitu-od-necistih-sila.html',
  './pokajna-molitva.html',
  './molitva-za-oprostaj-greha.html',
  './molitva-presvetoj-bogorodici-brzopomocnici.html',
  './molitve-za-svetu-tajnu-braku.html',
  './molitva-presvetoj-bogorodici-u-nevolji-i-potistenosti.html',
  './molitvе-svetom-vasiliju-ostroskom.html',
  './molitva-protiv-hulnih-pomisli.html',
  './zahvalna-molitva.html',
  './molitva-za-umnozenje-ljubavi.html',
  './molitva-za-one-koji-putuju.html',
  './molitva-svetom-naumu-ohridskom-cudotvorcu.html',
  './molitva-za-bolesnika.html',
  './molitva-pred-ispovest.html',
  './podsetnik-za-ispovest.html',
  './molitva-pred-sveto-pricesce.html',
  './molitva-posle-svetog-pricesca.html',
  './molitve-pre-i-posle-ucenja.html',
  './molitve-pre-spavanja.html',
  './molitva-pre-uzimanja-nafore-i-svete-vode.html',
  './hrabrost-za-molitvu.html',
  './ucenje-starca-vasilija-o-isusovoj-molitvi.html'
 
];

// Ostatak skripte (install, activate, fetch) je dobar i ne moraš ga menjati, 
// samo neka ostane onako kako si mi poslala ispod ovog spiska!

self.addEventListener('install', evt => {
  self.skipWaiting(); 
  evt.waitUntil(
    caches.open(cacheName).then(cache => {
      return cache.addAll(assets);
    })
  );
});

self.addEventListener('activate', evt => {
  evt.waitUntil(
    caches.keys().then(keys => {
      return Promise.all(keys
        .filter(key => key !== cacheName)
        .map(key => caches.delete(key))
      );
    })
  );
});

self.addEventListener('fetch', evt => {
  evt.respondWith(
    caches.match(evt.request).then(cacheRes => {
      return cacheRes || fetch(evt.request).then(fetchRes => {
        return caches.open(cacheName).then(cache => {
          cache.put(evt.request.url, fetchRes.clone());
          return fetchRes;
        });
      });
    }).catch(() => {
    if (evt.request.url.indexOf('.html') > -1) {
        return caches.match('./index.html');
      }
    })
  );
});
